POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/ce173a50-fcd0-416a-9091-c23879dec746
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/confirmed?pageSize=2&pageNumber=0
Accept: application/json
Content-Type: application/json
