POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/b42f0398-3d43-45f0-adcd-e112ca9e7505
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/confirmed?pageSize=2&pageNumber=0
Accept: application/json
Content-Type: application/json
