server:
  port: 8000
spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    # hibernate:
      # ddl-auto: create-drop
    show-sql: true
  messages:
    basename: exceptions
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/h2.db
    username: admin
    password: admin
    # url: jdbc:postgresql://localhost:5432/shop
    # username: admin
    # password: admin
    # driver-class-name: org.postgresql.Driver
  mongodb:
    embedded:
      version: 3.4.6
  data:
    mongodb:
      port: 30000
  profiles:
    active: development
logging:
  level:
    org.javamoney.moneta.FastMoney: OFF
time-api:
  endpoint: http://worldtimeapi.org/api/timezone
  timezone: Europe/Warsaw
  token: 1234
---
spring:
  config:
    activate:
      on-profile: development
logging:
  level:
    pl.training.shop: DEBUG
feign:
  client:
    config:
      timeProvider:
        logger-level: headers
